variable "host_project" {}
variable "service_project01" {}
variable "subnetname" {}
variable "cidr_range" {}
variable "region" {}
variable "project_name" {}
variable "network_name" {}
variable "secondary_pod_name" {}
variable "secondary_pod_cidr_range" {}
variable "secondary_service_name" {}
variable "secondary_service_cidr_range" {}
